language: ruby
sudo: false
rvm: 2.5.1
env:
  matrix:
  - QUEUE=docker DIST=trusty
  global:
  - CHIRP_SUMMARY_OUTPUT="${TRAVIS_BUILD_DIR}/chirp.json"
  - SITE=org
addons: { apt: { packages: [bc] } }
linux_shared: &linux_shared
  os: linux
  addons: { apt: { packages: [bc] } }
matrix:
  include:
  - sudo: false
    dist: trusty
    env: QUEUE=ec2 DIST=trusty
    <<: *linux_shared
  - sudo: required
    dist: trusty
    env: QUEUE=gce DIST=trusty
    <<: *linux_shared
  - sudo: required
    dist: xenial
    group: edge
    env: QUEUE=gce DIST=xenial
    <<: *linux_shared
before_install:
- gem update --system
- gem install bundler
script:
- bundle exec chirp scripts
- type travis_whereami
- travis_whereami
after_failure: bundle exec chirp dumplogs
