language: ruby
sudo: false
rvm: 2.5.1
env:
  matrix:
  - QUEUE=docker DIST=trusty
  global:
  - CHIRP_SUMMARY_OUTPUT="${TRAVIS_BUILD_DIR}/chirp.json"
  - SITE=org
addons:
  apt: { packages: [bc, iperf3] }
  homebrew: { packages: [iperf3] }
linux_shared: &linux_shared
  os: linux
  addons: { apt: { packages: [bc, iperf3] } }
matrix:
  include:
  - sudo: false
    dist: trusty
    env: QUEUE=ec2 DIST=trusty
    <<: *linux_shared
  - sudo: required
    dist: trusty
    env: QUEUE=gce DIST=trusty
    <<: *linux_shared
  - sudo: required
    dist: xenial
    group: edge
    env: QUEUE=gce DIST=xenial
    <<: *linux_shared
  - os: osx
    rvm: default
    env: QUEUE=macstadium6 IMAGE=default
  - os: osx
    osx_image: xcode7
    rvm: default
    env: QUEUE=macstadium6 IMAGE=xcode7
before_install:
- gem update --system
- gem install bundler
- |
  if command -v gcloud &>/dev/null; then
    openssl aes-256-cbc -K $encrypted_3cb1ee05e542_key -iv $encrypted_3cb1ee05e542_iv -in gs-travis-chirp.json.enc -out gs-travis-chirp.json -d
    gcloud auth activate-service-account "$(jq -r .client_email <gs-travis-chirp.json)" --key-file $(pwd)/gs-travis-chirp.json
  fi
script: bundle exec chirp scripts
after_script: bundle exec chirp sendstats 2>/dev/null
after_failure: bundle exec chirp dumplogs
